export const products = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    vendor: "TechGear Store",
    price: 799.99,
    originalPrice: 999.99,
    rating: 4.8,
    reviews: 124,
    image: "/wireless-bluetooth-headphones.jpg",
    badge: "Sale",
    category: "Electronics",
    description:
      "Premium wireless headphones with active noise cancellation, 30-hour battery life, and crystal-clear audio quality. Perfect for music lovers and professionals who demand the best sound experience.",
    stock: 45,
  },
  {
    id: "2",
    name: "Leather Laptop Bag",
    vendor: "Premium Accessories",
    price: 890.0,
    rating: 4.9,
    reviews: 87,
    image: "/leather-laptop-bag-brown.jpg",
    badge: "Bestseller",
    category: "Accessories",
    description:
      "Handcrafted genuine leather laptop bag with multiple compartments. Fits laptops up to 15.6 inches. Durable, stylish, and perfect for professionals on the go.",
    stock: 23,
  },
  {
    id: "3",
    name: "Stainless Steel Water Bottle",
    vendor: "EcoLife Essentials",
    price: 249.99,
    rating: 4.7,
    reviews: 203,
    image: "/stainless-steel-bottle.png",
    category: "Home & Kitchen",
    description:
      "Double-walled insulated water bottle keeps drinks cold for 24 hours or hot for 12 hours. BPA-free and eco-friendly. Perfect for gym, office, or outdoor activities.",
    stock: 156,
  },
  {
    id: "4",
    name: "Smart Fitness Watch",
    vendor: "TechGear Store",
    price: 1490.0,
    originalPrice: 1990.0,
    rating: 4.6,
    reviews: 156,
    image: "/smart-fitness-watch-black.jpg",
    badge: "New",
    category: "Electronics",
    description:
      "Track your fitness goals with this advanced smartwatch. Features heart rate monitoring, GPS, sleep tracking, and 7-day battery life. Water-resistant and compatible with iOS and Android.",
    stock: 67,
  },
  {
    id: "5",
    name: "Organic Cotton T-Shirt",
    vendor: "Green Threads",
    price: 299.99,
    rating: 4.8,
    reviews: 312,
    image: "/organic-cotton-t-shirt.jpg",
    badge: "Bestseller",
    category: "Fashion",
    description:
      "Soft, breathable organic cotton t-shirt. Sustainably sourced and ethically made. Available in multiple colors and sizes. Perfect for everyday wear.",
    stock: 234,
  },
  {
    id: "6",
    name: "Bamboo Desk Organizer",
    vendor: "EcoLife Essentials",
    price: 345.0,
    rating: 4.7,
    reviews: 89,
    image: "/bamboo-desk-organizer.jpg",
    category: "Home & Kitchen",
    description:
      "Eco-friendly bamboo desk organizer with multiple compartments for pens, pencils, and office supplies. Sleek design that fits any workspace aesthetic.",
    stock: 78,
  },
  {
    id: "7",
    name: "Professional Chef Knife Set",
    vendor: "Kitchen Masters",
    price: 1299.99,
    rating: 4.9,
    reviews: 67,
    image: "/professional-chef-knife-set.jpg",
    badge: "New",
    category: "Home & Kitchen",
    description:
      "Premium 8-piece chef knife set with high-carbon stainless steel blades. Includes chef knife, paring knife, utility knife, and more. Comes with a wooden storage block.",
    stock: 34,
  },
  {
    id: "8",
    name: "Yoga Mat with Carrying Strap",
    vendor: "FitLife Pro",
    price: 399.99,
    originalPrice: 549.99,
    rating: 4.6,
    reviews: 178,
    image: "/yoga-mat-purple.jpg",
    badge: "Sale",
    category: "Sports & Fitness",
    description:
      "Non-slip yoga mat with extra cushioning. Made from eco-friendly TPE material. Includes carrying strap and storage bag. Perfect for yoga, pilates, and general fitness.",
    stock: 89,
  },
  {
    id: "9",
    name: "Portable Phone Charger 20000mAh",
    vendor: "TechGear Store",
    price: 459.99,
    rating: 4.8,
    reviews: 234,
    image: "/portable-phone-charger-powerbank.jpg",
    category: "Electronics",
    description:
      "High-capacity portable charger with dual USB ports and fast charging technology. Can charge most phones 4-5 times. LED display shows remaining battery. TSA-approved for air travel.",
    stock: 123,
  },
  {
    id: "10",
    name: "Ceramic Coffee Mug Set",
    vendor: "Home Essentials Co",
    price: 320.0,
    rating: 4.7,
    reviews: 145,
    image: "/ceramic-coffee-mugs-colorful.jpg",
    badge: "Bestseller",
    category: "Home & Kitchen",
    description:
      "Set of 4 handcrafted ceramic coffee mugs. Each holds 12oz. Microwave and dishwasher safe. Beautiful glazed finish in assorted colors. Makes a great gift.",
    stock: 67,
  },
  {
    id: "11",
    name: "Running Shoes - Men's",
    vendor: "FitLife Pro",
    price: 899.99,
    originalPrice: 1200.0,
    rating: 4.8,
    reviews: 267,
    image: "/running-shoes-mens-athletic.jpg",
    badge: "Sale",
    category: "Sports & Fitness",
    description:
      "Lightweight running shoes with responsive cushioning and breathable mesh upper. Durable rubber outsole provides excellent traction. Available in multiple sizes and colors.",
    stock: 45,
  },
  {
    id: "12",
    name: "Scented Candle Gift Set",
    vendor: "Home Essentials Co",
    price: 449.99,
    rating: 4.9,
    reviews: 198,
    image: "/scented-candles-gift-set.jpg",
    category: "Home & Kitchen",
    description:
      "Luxury scented candle set with 6 unique fragrances. Made from natural soy wax with lead-free cotton wicks. Burns for 25-30 hours each. Beautifully packaged for gifting.",
    stock: 56,
  },
  {
    id: "13",
    name: "Wireless Gaming Mouse",
    vendor: "TechGear Store",
    price: 549.99,
    rating: 4.7,
    reviews: 189,
    image: "/wireless-gaming-mouse-rgb.jpg",
    category: "Electronics",
    description:
      "High-precision wireless gaming mouse with customizable RGB lighting and programmable buttons. Ergonomic design for long gaming sessions.",
    stock: 78,
  },
  {
    id: "14",
    name: "USB-C Hub Multi-Port Adapter",
    vendor: "TechGear Store",
    price: 349.99,
    rating: 4.6,
    reviews: 156,
    image: "/usb-c-hub-adapter-ports.jpg",
    category: "Electronics",
    description:
      "7-in-1 USB-C hub with HDMI, USB 3.0 ports, SD card reader, and 100W power delivery. Perfect for laptops and tablets.",
    stock: 92,
  },
  {
    id: "15",
    name: "Bluetooth Speaker Waterproof",
    vendor: "TechGear Store",
    price: 649.99,
    originalPrice: 899.99,
    rating: 4.9,
    reviews: 267,
    image: "/waterproof-bluetooth-speaker-outdoor.jpg",
    badge: "Sale",
    category: "Electronics",
    description:
      "Portable waterproof speaker with 360-degree sound and 12-hour battery life. IPX7 rated for outdoor adventures.",
    stock: 54,
  },
  {
    id: "16",
    name: "Classic Denim Jacket",
    vendor: "Fashion Forward",
    price: 899.99,
    rating: 4.7,
    reviews: 198,
    image: "/denim-jacket-blue-classic.jpg",
    category: "Fashion",
    description:
      "Timeless denim jacket with a modern fit. Made from durable cotton blend. Perfect for layering in any season.",
    stock: 67,
  },
  {
    id: "17",
    name: "Floral Summer Dress",
    vendor: "Fashion Forward",
    price: 699.99,
    rating: 4.8,
    reviews: 243,
    image: "/floral-summer-dress-colorful.jpg",
    badge: "Bestseller",
    category: "Fashion",
    description:
      "Lightweight floral dress perfect for summer. Breathable fabric with adjustable straps and a flattering fit.",
    stock: 89,
  },
  {
    id: "18",
    name: "Slim Fit Chinos",
    vendor: "Fashion Forward",
    price: 799.99,
    rating: 4.6,
    reviews: 156,
    image: "/chinos-pants-slim-fit-beige.jpg",
    category: "Fashion",
    description:
      "Versatile slim-fit chinos in premium stretch cotton. Perfect for both casual and semi-formal occasions.",
    stock: 124,
  },
  {
    id: "19",
    name: "Leather Belt Classic",
    vendor: "Fashion Forward",
    price: 449.99,
    rating: 4.7,
    reviews: 178,
    image: "/leather-belt-brown-classic.jpg",
    category: "Fashion",
    description: "Genuine leather belt with a classic silver buckle. Durable and stylish, suitable for any outfit.",
    stock: 145,
  },
  {
    id: "20",
    name: "Winter Wool Coat",
    vendor: "Fashion Forward",
    price: 1899.99,
    originalPrice: 2499.99,
    rating: 4.9,
    reviews: 89,
    image: "/wool-coat-winter-black-elegant.jpg",
    badge: "Sale",
    category: "Fashion",
    description:
      "Elegant wool coat for cold weather. Premium fabric with a tailored fit. Includes belt and deep pockets.",
    stock: 34,
  },
  {
    id: "21",
    name: "Sterling Silver Necklace",
    vendor: "Elegant Gems",
    price: 899.99,
    rating: 4.8,
    reviews: 267,
    image: "/sterling-silver-necklace-pendant.jpg",
    badge: "New",
    category: "Jewelry",
    description:
      "Beautiful sterling silver necklace with delicate pendant. Hypoallergenic and tarnish-resistant. Comes in a gift box.",
    stock: 78,
  },
  {
    id: "22",
    name: "Gold Plated Hoop Earrings",
    vendor: "Elegant Gems",
    price: 549.99,
    rating: 4.9,
    reviews: 345,
    image: "/gold-hoop-earrings-large.jpg",
    badge: "Bestseller",
    category: "Jewelry",
    description:
      "Classic gold-plated hoop earrings. Lightweight and comfortable for all-day wear. Perfect for any occasion.",
    stock: 156,
  },
  {
    id: "23",
    name: "Diamond Stud Earrings",
    vendor: "Elegant Gems",
    price: 1299.99,
    rating: 5.0,
    reviews: 198,
    image: "/diamond-stud-earrings-small-elegant.jpg",
    category: "Jewelry",
    description:
      "Elegant diamond stud earrings set in white gold. Lab-grown diamonds with excellent clarity. Includes certificate.",
    stock: 45,
  },
  {
    id: "24",
    name: "Beaded Bracelet Set",
    vendor: "Elegant Gems",
    price: 349.99,
    rating: 4.7,
    reviews: 234,
    image: "/beaded-bracelet-colorful-set.jpg",
    category: "Jewelry",
    description:
      "Set of 3 handmade beaded bracelets. Natural stones and adjustable fit. Perfect for stacking or wearing individually.",
    stock: 189,
  },
  {
    id: "25",
    name: "Rose Gold Ring",
    vendor: "Elegant Gems",
    price: 799.99,
    rating: 4.8,
    reviews: 156,
    image: "/rose-gold-ring-band-simple.jpg",
    category: "Jewelry",
    description:
      "Minimalist rose gold ring with a polished finish. Available in multiple sizes. Perfect for everyday elegance.",
    stock: 98,
  },
  {
    id: "26",
    name: "Pearl Necklace Classic",
    vendor: "Elegant Gems",
    price: 1099.99,
    originalPrice: 1499.99,
    rating: 4.9,
    reviews: 123,
    image: "/pearl-necklace-white-classic.jpg",
    badge: "Sale",
    category: "Jewelry",
    description:
      "Timeless freshwater pearl necklace. Hand-knotted with silk thread and silver clasp. A sophisticated addition to any wardrobe.",
    stock: 56,
  },
  {
    id: "27",
    name: "Sunglasses Aviator Style",
    vendor: "Premium Accessories",
    price: 449.99,
    rating: 4.7,
    reviews: 289,
    image: "/aviator-sunglasses-silver.jpg",
    category: "Accessories",
    description:
      "Classic aviator sunglasses with UV400 protection. Metal frame with gradient lenses. Includes protective case.",
    stock: 167,
  },
  {
    id: "28",
    name: "Leather Wallet Bifold",
    vendor: "Premium Accessories",
    price: 349.99,
    rating: 4.8,
    reviews: 345,
    image: "/leather-wallet-bifold-brown.jpg",
    badge: "Bestseller",
    category: "Accessories",
    description:
      "Premium leather bifold wallet with multiple card slots and bill compartments. RFID blocking for added security.",
    stock: 234,
  },
  {
    id: "29",
    name: "Canvas Backpack",
    vendor: "Premium Accessories",
    price: 649.99,
    rating: 4.6,
    reviews: 178,
    image: "/placeholder.svg?height=400&width=400",
    category: "Accessories",
    description:
      "Vintage-style canvas backpack with leather accents. Multiple pockets and padded laptop compartment. Perfect for daily use.",
    stock: 89,
  },
  {
    id: "30",
    name: "Silk Scarf Luxury",
    vendor: "Premium Accessories",
    price: 549.99,
    rating: 4.9,
    reviews: 198,
    image: "/placeholder.svg?height=400&width=400",
    category: "Accessories",
    description:
      "Luxurious silk scarf with hand-rolled edges. Versatile styling options for any season. Beautiful floral pattern.",
    stock: 112,
  },
  {
    id: "31",
    name: "Watch Strap Leather",
    vendor: "Premium Accessories",
    price: 249.99,
    rating: 4.7,
    reviews: 156,
    image: "/placeholder.svg?height=400&width=400",
    category: "Accessories",
    description:
      "Premium leather watch strap compatible with most standard watches. Quick-release spring bars included.",
    stock: 145,
  },
  {
    id: "32",
    name: "Cast Iron Skillet",
    vendor: "Kitchen Masters",
    price: 549.99,
    rating: 4.8,
    reviews: 234,
    image: "/placeholder.svg?height=400&width=400",
    category: "Home & Kitchen",
    description:
      "Pre-seasoned cast iron skillet. Even heat distribution and naturally non-stick. Perfect for stovetop and oven use.",
    stock: 78,
  },
  {
    id: "33",
    name: "Resistance Bands Set",
    vendor: "FitLife Pro",
    price: 299.99,
    rating: 4.7,
    reviews: 289,
    image: "/placeholder.svg?height=400&width=400",
    category: "Sports & Fitness",
    description:
      "Set of 5 resistance bands with different resistance levels. Includes door anchor and carry bag. Perfect for home workouts.",
    stock: 167,
  },
  {
    id: "34",
    name: "Adjustable Dumbbells Pair",
    vendor: "FitLife Pro",
    price: 1499.99,
    rating: 4.9,
    reviews: 156,
    image: "/placeholder.svg?height=400&width=400",
    badge: "New",
    category: "Sports & Fitness",
    description:
      "Space-saving adjustable dumbbells. Each adjusts from 5 to 25 lbs. Quick-change weight selection system.",
    stock: 45,
  },
  {
    id: "35",
    name: "Jump Rope Speed",
    vendor: "FitLife Pro",
    price: 199.99,
    rating: 4.6,
    reviews: 234,
    image: "/placeholder.svg?height=400&width=400",
    category: "Sports & Fitness",
    description:
      "Professional speed jump rope with ball bearings. Adjustable length and comfortable handles. Great for cardio workouts.",
    stock: 198,
  },
  {
    id: "36",
    name: "Exercise Ball 65cm",
    vendor: "FitLife Pro",
    price: 349.99,
    rating: 4.7,
    reviews: 178,
    image: "/placeholder.svg?height=400&width=400",
    category: "Sports & Fitness",
    description: "Anti-burst exercise ball for yoga, pilates, and core training. Includes pump and workout guide.",
    stock: 123,
  },
]

export const vendors = [
  {
    id: 1,
    name: "TechGear Store",
    location: "San Francisco, CA",
    rating: 4.8,
    reviews: 514,
    products: 128,
    image: "/tech-store-logo.png",
    verified: true,
  },
  {
    id: 2,
    name: "Premium Accessories",
    location: "New York, NY",
    rating: 4.9,
    reviews: 289,
    products: 67,
    image: "/accessories-store-logo.jpg",
    verified: true,
  },
  {
    id: 3,
    name: "EcoLife Essentials",
    location: "Portland, OR",
    rating: 4.7,
    reviews: 456,
    products: 203,
    image: "/eco-friendly-store-logo.png",
    verified: true,
  },
  {
    id: 4,
    name: "Kitchen Masters",
    location: "Chicago, IL",
    rating: 4.9,
    reviews: 378,
    products: 145,
    image: "/kitchen-store-logo.png",
    verified: true,
  },
  {
    id: 5,
    name: "Fashion Forward",
    location: "Los Angeles, CA",
    rating: 4.8,
    reviews: 312,
    products: 156,
    image: "/leather-wallet-bifold-brown.jpg",
    verified: true,
  },
  {
    id: 6,
    name: "Elegant Gems",
    location: "Miami, FL",
    rating: 4.9,
    reviews: 267,
    products: 203,
    image: "/diamond-stud-earrings-small-elegant.jpg",
    verified: true,
  },
]
