export const products = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    vendor: "TechGear Store",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.8,
    reviews: 124,
    image: "/wireless-bluetooth-headphones.jpg",
    badge: "Sale",
  },
  {
    id: 2,
    name: "Leather Laptop Bag",
    vendor: "Premium Accessories",
    price: 89.0,
    rating: 4.9,
    reviews: 87,
    image: "/leather-laptop-bag-brown.jpg",
    badge: "Bestseller",
  },
  {
    id: 3,
    name: "Stainless Steel Water Bottle",
    vendor: "EcoLife Essentials",
    price: 24.99,
    rating: 4.7,
    reviews: 203,
    image: "/stainless-steel-bottle.png",
  },
  {
    id: 4,
    name: "Smart Fitness Watch",
    vendor: "TechGear Store",
    price: 149.0,
    originalPrice: 199.0,
    rating: 4.6,
    reviews: 156,
    image: "/smart-fitness-watch-black.jpg",
    badge: "New",
  },
  {
    id: 5,
    name: "Organic Cotton T-Shirt",
    vendor: "Green Threads",
    price: 29.99,
    rating: 4.8,
    reviews: 312,
    image: "/organic-cotton-t-shirt.jpg",
    badge: "Bestseller",
  },
  {
    id: 6,
    name: "Bamboo Desk Organizer",
    vendor: "EcoLife Essentials",
    price: 34.5,
    rating: 4.7,
    reviews: 89,
    image: "/bamboo-desk-organizer.jpg",
  },
  {
    id: 7,
    name: "Professional Chef Knife Set",
    vendor: "Kitchen Masters",
    price: 129.99,
    rating: 4.9,
    reviews: 67,
    image: "/professional-chef-knife-set.jpg",
    badge: "New",
  },
  {
    id: 8,
    name: "Yoga Mat with Carrying Strap",
    vendor: "FitLife Pro",
    price: 39.99,
    originalPrice: 54.99,
    rating: 4.6,
    reviews: 178,
    image: "/yoga-mat-purple.jpg",
    badge: "Sale",
  },
  {
    id: 9,
    name: "Portable Phone Charger 20000mAh",
    vendor: "TechGear Store",
    price: 45.99,
    rating: 4.8,
    reviews: 234,
    image: "/portable-phone-charger-powerbank.jpg",
  },
  {
    id: 10,
    name: "Ceramic Coffee Mug Set",
    vendor: "Home Essentials Co",
    price: 32.0,
    rating: 4.7,
    reviews: 145,
    image: "/ceramic-coffee-mugs-colorful.jpg",
    badge: "Bestseller",
  },
  {
    id: 11,
    name: "Running Shoes - Men's",
    vendor: "FitLife Pro",
    price: 89.99,
    originalPrice: 120.0,
    rating: 4.8,
    reviews: 267,
    image: "/running-shoes-mens-athletic.jpg",
    badge: "Sale",
  },
  {
    id: 12,
    name: "Scented Candle Gift Set",
    vendor: "Home Essentials Co",
    price: 44.99,
    rating: 4.9,
    reviews: 198,
    image: "/scented-candles-gift-set.jpg",
  },
]

export const vendors = [
  {
    id: 1,
    name: "TechGear Store",
    location: "San Francisco, CA",
    rating: 4.8,
    reviews: 514,
    products: 128,
    image: "/tech-store-logo.png",
    verified: true,
  },
  {
    id: 2,
    name: "Premium Accessories",
    location: "New York, NY",
    rating: 4.9,
    reviews: 289,
    products: 67,
    image: "/accessories-store-logo.jpg",
    verified: true,
  },
  {
    id: 3,
    name: "EcoLife Essentials",
    location: "Portland, OR",
    rating: 4.7,
    reviews: 456,
    products: 203,
    image: "/eco-friendly-store-logo.png",
    verified: true,
  },
  {
    id: 4,
    name: "Kitchen Masters",
    location: "Chicago, IL",
    rating: 4.9,
    reviews: 378,
    products: 145,
    image: "/kitchen-store-logo.png",
    verified: true,
  },
]
